apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
        - name: oracle-db-container
          image: gvenzl/oracle-free:latest
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_PASSWORD
              value: "Tien22012003@"
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: oracle-storage
      volumes:
        - name: oracle-storage
          persistentVolumeClaim:
            claimName: oracle-pvc
