version: "3.8"

services:
  rust:
    image: rust:latest
    container_name: rust-container
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - pro_prj_net

networks:
  pro_prj_net:
    driver: bridge
