version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: code_gym_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code_gym
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    networks:
      - pro_prj_net

volumes:
  mysql_data:

networks:
  pro_prj_net:
    driver: bridge