/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myself_programing_coding_TestCallCLib */

#ifndef _Included_myself_programing_coding_TestCallCLib
#define _Included_myself_programing_coding_TestCallCLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myself_programing_coding_TestCallCLib
 * Method:    fib
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_myself_programing_coding_TestCallCLib_fib
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
